package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/NON_EXISTENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from e:/jenkins/tmp/workspace/build/src/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, January 19, 2022 7:08:15 AM CST
*/

public interface NON_EXISTENT
{

  /** Object adapter state indicating that the adapter has been destroyed.
   */
  public static final short value = (short)(4);
}
